### ISSUE TITLE
AT&T 

### ISSUE THREAD

**Issue by soxrok2212** [veryfancypants/wpa_server#1]
Hey there, long time no see. I know this isn’t necessarily the proper manner to reach out to you but we’re looking at the AT&T gateways again, looking for some of your input. Interested?

**Comment by veryfancypants** [comment]
might be... were there any new developments?

**Comment by soxrok2212** [comment]
I’d say so. We have lots and lots of information but are hitting walls when trying to make sense of it. We’re on discord but can accommodate email or IRC if you’re into that and are interested!

**Comment by veryfancypants** [comment]
discord works

**Comment by soxrok2212** [comment]
soxrok2212#4522
